### PR TITLE
Upgrade to v0.14.0 of Syna theme

### PR DESCRIPTION
**Pull request by mpourismaiel**
- No breaking changes concerning the starter
- Links to documentation updated [need demo to be updated]
- Build files updated

### CODE REVIEW

**Comment by stp-ip** [comment]
* [ ] decide on v0.14 branch vs tag
* [ ] decide on /docs/ prerelease

**Comment by mpourismaiel** [comment]
Switched to v0.14 branch. Also changed the docs links to Github. Perhaps changing the docs would be a good idea. It would take some time but at least the release would be clean.
Also Hugo-v0.50 created some problems for us. I'm working on it so maybe we can wait on this PR a little longer?

**Comment by mpourismaiel** [comment]
Okay this should be done now.

**Comment by stp-ip** [comment]
\o/

**Pull request merged**
